import { chromium } from '@playwright/test';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=swiftshader', '--enable-webgl', '--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 900, height: 520 } });
await p.goto(process.env.URL || 'http://localhost:4175/', { waitUntil: 'networkidle' });
await p.waitForFunction(() => !!window.__game);
await p.waitForTimeout(5000);
const n = await p.evaluate(() => window.__game.state.customers.length);
await p.screenshot({ path: 'e2e/service.png' });
await b.close();
console.log('customers seated:', n);
